package invoice.management.system.utils

import com.neovisionaries.i18n.CountryCode

enum class CountryCodes(val countryName: String, val countryCode: CountryCode) {
    ANDORRA("Andorra, Principality Of", CountryCode.AD),
    UAE("United Arab Emirates", CountryCode.AE),
    AFGHANISTAN("Afghanistan, Islamic State Of", CountryCode.AF),
    ANTIGUA_AND_BARBUDA("Antigua And Barbuda", CountryCode.AG),
    ANGUILLA("Anguilla", CountryCode.AI),
    ALBANIA("Albania", CountryCode.AL),
    ARMENIA("Armenia", CountryCode.AM),
    NETHERLANDS_ANTILLES("Netherlands Antilles", CountryCode.AN),
    ANGOLA("Angola", CountryCode.AO),
    ANTARCTICA("Antarctica", CountryCode.AQ),
    ARGENTINA("Argentina", CountryCode.AR),
    AMERICAN_SAMOA("American Samoa", CountryCode.AS),
    AUSTRIA("Austria", CountryCode.AT),
    AUSTRALIA("Australia", CountryCode.AU),
    ARUBA("Aruba", CountryCode.AW),
    AZERBAIDJAN("Azerbaidjan", CountryCode.AZ),
    BOSNIA_HERZEGOVINA("Bosnia-Herzegovina", CountryCode.BA),
    BARBADOS("Barbados", CountryCode.BB),
    BANGLADESH("Bangladesh", CountryCode.BD),
    BELGIUM("Belgium", CountryCode.BE),
    BURKINA_FASO("Burkina Faso", CountryCode.BF),
    BULGARIA("Bulgaria", CountryCode.BG),
    BAHRAIN("Bahrain", CountryCode.BH),
    BURUNDI("Burundi", CountryCode.BI),
    BENIN("Benin", CountryCode.BJ),
    BERMUDA("Bermuda", CountryCode.BM),
    BRUNEI("Brunei Darussalam", CountryCode.BN),
    BOLIVIA("Bolivia", CountryCode.BO),
    BRAZIL("Brazil", CountryCode.BR),
    BAHAMAS("Bahamas", CountryCode.BS),
    BHUTAN("Bhutan", CountryCode.BT),
    BOUVET_ISLAND("Bouvet Island", CountryCode.BV),
    BOTSWANA("Botswana", CountryCode.BW),
    BELARUS("Belarus", CountryCode.BY),
    BELIZE("Belize", CountryCode.BZ),
    CANADA("Canada", CountryCode.CA),
    COCOS_ISLANDS("Cocos (Keeling) Islands", CountryCode.CC),
    CENTRAL_AFRICAN_REPUBLIC("Central African Republic", CountryCode.CF),
    DRC("Congo, The Democratic Republic Of The", CountryCode.CD),
    CONGO("Congo", CountryCode.CG),
    SWITZERLAND("Switzerland", CountryCode.CH),
    COTE_DIVOIRE("Ivory Coast (Cote D'Ivoire)", CountryCode.CI),
    COOK_ISLANDS("Cook Islands", CountryCode.CK),
    CHILE("Chile", CountryCode.CL),
    CAMEROON("Cameroon", CountryCode.CM),
    CHINA("China", CountryCode.CN),
    COLOMBIA("Colombia", CountryCode.CO),
    COSTA_RICA("Costa Rica", CountryCode.CR),
    CZECHOSLOVAKIA("Former Czechoslovakia", CountryCode.CS),
    CUBA("Cuba", CountryCode.CU),
    CAPE_VERDE("Cape Verde", CountryCode.CV),
    CHRISTMAS_ISLAND("Christmas Island", CountryCode.CX),
    CYPRUS("Cyprus", CountryCode.CY),
    CZECH_REPUBLIC("Czech Republic", CountryCode.CZ),
    GERMANY("Germany", CountryCode.DE),
    DJIBOUTI("Djibouti", CountryCode.DJ),
    DENMARK("Denmark", CountryCode.DK),
    DOMINICA("Dominica", CountryCode.DM),
    DOMINICAN_REPUBLIC("Dominican Republic", CountryCode.DO),
    ALGERIA("Algeria", CountryCode.DZ),
    ECUADOR("Ecuador", CountryCode.EC),
    ESTONIA("Estonia", CountryCode.EE),
    EGYPT("Egypt", CountryCode.EG),
    WESTERN_SAHARA("Western Sahara", CountryCode.EH),
    ERITREA("Eritrea", CountryCode.ER),
    SPAIN("Spain", CountryCode.ES),
    ETHIOPIA("Ethiopia", CountryCode.ET),
    FINLAND("Finland", CountryCode.FI),
    FIJI("Fiji", CountryCode.FJ),
    FALKLAND_ISLANDS("Falkland Islands", CountryCode.FK),
    MICRONESIA("Micronesia", CountryCode.FM),
    FAROE_ISLANDS("Faroe Islands", CountryCode.FO),
    FRANCE("France", CountryCode.FR),
    FRENCH_TERRITORY("France (European Territory)", CountryCode.FX),
    GABON("Gabon", CountryCode.GA),
    UK("Great Britain", CountryCode.GB),
    GRENADA("Grenada", CountryCode.GD),
    GEORGIA("Georgia", CountryCode.GE),
    FRENCH_GUYANA("French Guyana", CountryCode.GF),
    GHANA("Ghana", CountryCode.GH),
    GIBRALTAR("Gibraltar", CountryCode.GI),
    GREENLAND("Greenland", CountryCode.GL),
    GAMBIA("Gambia", CountryCode.GM),
    GUINEA("Guinea", CountryCode.GN)
}
